# Copyright (c) 2026, Finstein and contributors
# For license information, please see license.txt
"""All custom fields this app adds to core doctypes. Idempotent: re-run on every migrate."""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields as _create

CUSTOM_FIELDS = {
	"Pick List": [
		{
			"fieldname": "mp_spool_section",
			"fieldtype": "Section Break",
			"label": "Spool / Reel Tracking",
			"insert_after": "locations",
			"collapsible": 1,
		},
		{
			"fieldname": "mp_scan_spool",
			"fieldtype": "Data",
			"label": "Scan Spool U-ID",
			"insert_after": "mp_spool_section",
			"allow_on_submit": 0,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_spool_details",
			"fieldtype": "Table",
			"label": "Spools",
			"options": "Pick List Spool Detail",
			"insert_after": "mp_scan_spool",
			"no_copy": 1,
		},
	],
	"Batch": [
		{
			"fieldname": "custom_spool_section",
			"fieldtype": "Section Break",
			"label": "Spool / Reel Details",
			"insert_after": "batch_qty",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_spool_details",
			"fieldtype": "Table",
			"label": "Spool Details",
			"options": "Spool Details",
			"insert_after": "custom_spool_section",
		},
	],
	"Item": [
		{
			"fieldname": "mp_package",
			"fieldtype": "Link",
			"label": "Pick List Package",
			"options": "MP Item Package",
			"insert_after": "stock_uom",
			"no_copy": 1,
			"description": "Drives the Pick List buffer slabs",
		},
		{
			"fieldname": "mp_item_class",
			"fieldtype": "Select",
			"label": "Item Class (ABC)",
			"options": "\nA\nB\nC",
			"insert_after": "mp_package",
			"no_copy": 1,
			"description": "Used by the MOQ class threshold in Auto Purchase",
		},
	],
	"Work Order": [
		{
			"fieldname": "mp_buffer_qty",
			"fieldtype": "Float",
			"label": "Pick List Buffer Qty",
			"insert_after": "qty",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
			"precision": "3",
		},
	],
	"Stock Entry": [
		{
			"fieldname": "mp_source_purchase_receipt",
			"fieldtype": "Link",
			"label": "Source Purchase Receipt",
			"options": "Purchase Receipt",
			"insert_after": "purpose",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_combo_parts",
			"fieldtype": "Link",
			"label": "Combo Parts",
			"options": "Combo Parts",
			"insert_after": "mp_source_purchase_receipt",
			"read_only": 1,
			"no_copy": 1,
		},
	],
	"Sales Order Item": [
		{
			"fieldname": "mp_expected_delivery_date",
			"fieldtype": "Date",
			"label": "Expected Delivery Date (Computed)",
			"insert_after": "delivery_date",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_calc_status",
			"fieldtype": "Select",
			"label": "Calculation Status",
			"options": "\nComputed\nNo BOM\nPurchased Item\nService Item\nPartial Data\nSkipped\nFailed",
			"insert_after": "mp_expected_delivery_date",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_rm_lead_days",
			"fieldtype": "Int",
			"label": "RM Lead Days",
			"insert_after": "mp_calc_status",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_queue_days",
			"fieldtype": "Float",
			"label": "Queue Days",
			"precision": "3",
			"insert_after": "mp_rm_lead_days",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_production_days",
			"fieldtype": "Float",
			"label": "Production Days",
			"precision": "3",
			"insert_after": "mp_queue_days",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_buffer_days",
			"fieldtype": "Int",
			"label": "Buffer Days",
			"insert_after": "mp_production_days",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_bom_used",
			"fieldtype": "Link",
			"label": "BOM Used",
			"options": "BOM",
			"insert_after": "mp_buffer_days",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_calc_breakdown",
			"fieldtype": "Long Text",
			"label": "Calculation Breakdown",
			"insert_after": "mp_bom_used",
			"read_only": 1,
			"allow_on_submit": 1,
			"hidden": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_material_status",
			"fieldtype": "Select",
			"label": "Material Status",
			"options": "\nNot Checked\nIn Stock\nShort\nOrdered\nPartially Ordered\nReceived",
			"insert_after": "mp_calc_breakdown",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_material_available_date",
			"fieldtype": "Date",
			"label": "Material Available Date",
			"insert_after": "mp_material_status",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_delivery_risk",
			"fieldtype": "Select",
			"label": "Delivery Risk",
			"options": "\nConfirmed\nAt Risk",
			"insert_after": "mp_material_available_date",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_delivery_gap_days",
			"fieldtype": "Int",
			"label": "Delivery Gap (Days)",
			"insert_after": "mp_delivery_risk",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
	],
	"Sales Order": [
		{
			"fieldname": "mp_get_expected_delivery_date",
			"fieldtype": "Button",
			"label": "Get Expected Delivery Date",
			"insert_after": "delivery_date",
			"description": "Works out the date for every item row and fills Delivery Date",
		},
		{
			"fieldname": "mp_max_expected_delivery_date",
			"fieldtype": "Date",
			"label": "Expected Delivery Date (Computed)",
			"insert_after": "delivery_date",
			"read_only": 1,
			"allow_on_submit": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_manual_delivery_date",
			"fieldtype": "Check",
			"label": "Delivery Dates Entered Manually",
			"insert_after": "mp_max_expected_delivery_date",
			"no_copy": 1,
		},
	],
	"Material Request Item": [
		# Data, not Link: a Link here would make a submitted MR block the Sales Order from
		# being cancelled. Traceability is kept through the reports instead.
		{
			"fieldname": "mp_so_reference",
			"fieldtype": "Data",
			"label": "Demand Sales Order",
			"insert_after": "sales_order_item",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_so_line",
			"fieldtype": "Data",
			"label": "Demand Sales Order Line",
			"insert_after": "mp_so_reference",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_fg_item_code",
			"fieldtype": "Link",
			"label": "For FG Item",
			"options": "Item",
			"insert_after": "mp_so_line",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_demand_key",
			"fieldtype": "Data",
			"label": "Demand Key",
			"insert_after": "mp_fg_item_code",
			"read_only": 1,
			"hidden": 1,
			"no_copy": 1,
		},
	],
	"Material Request": [
		{
			"fieldname": "mp_master_production_schedule",
			"fieldtype": "Link",
			"label": "Master Production Schedule",
			"options": "Master Production Schedule",
			"insert_after": "material_request_type",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_auto_purchase_run",
			"fieldtype": "Link",
			"label": "Auto Purchase Run",
			"options": "Auto Purchase Run",
			"insert_after": "material_request_type",
			"read_only": 1,
			"no_copy": 1,
		},
	],
	"Purchase Order": [
		{
			"fieldname": "mp_master_production_schedule",
			"fieldtype": "Link",
			"label": "Master Production Schedule",
			"options": "Master Production Schedule",
			"insert_after": "supplier",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_auto_purchase_run",
			"fieldtype": "Link",
			"label": "Auto Purchase Run",
			"options": "Auto Purchase Run",
			"insert_after": "supplier",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_auto_purchased",
			"fieldtype": "Check",
			"label": "Created By Auto Purchase",
			"insert_after": "mp_auto_purchase_run",
			"read_only": 1,
			"no_copy": 1,
		},
	],
	"Purchase Order Item": [
		# Data for the same reason as on Material Request Item.
		{
			"fieldname": "mp_so_reference",
			"fieldtype": "Data",
			"label": "Demand Sales Order",
			"insert_after": "material_request_item",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_so_line",
			"fieldtype": "Data",
			"label": "Demand Sales Order Line",
			"insert_after": "mp_so_reference",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_demand_key",
			"fieldtype": "Data",
			"label": "Demand Key",
			"insert_after": "mp_so_line",
			"read_only": 1,
			"hidden": 1,
			"no_copy": 1,
		},
	],
	"Master Production Schedule": [
		{
			"fieldname": "mp_sales_order",
			"fieldtype": "Link",
			"label": "Created From Sales Order",
			"options": "Sales Order",
			"insert_after": "sales_forecast",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_period_key",
			"fieldtype": "Data",
			"label": "Plan Period",
			"insert_after": "mp_sales_order",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_auto_purchase_run",
			"fieldtype": "Link",
			"label": "Auto Purchase Run",
			"options": "Auto Purchase Run",
			"insert_after": "mp_period_key",
			"read_only": 1,
			"no_copy": 1,
		},
		{
			"fieldname": "mp_auto_created",
			"fieldtype": "Check",
			"label": "Created By Auto Purchase",
			"insert_after": "mp_sales_order",
			"read_only": 1,
			"no_copy": 1,
		},
	],
}


def create_custom_fields():
	_create(CUSTOM_FIELDS, ignore_validate=True)
	frappe.clear_cache()
